-- Переехало в schema_control.sql (2026-09-12) — users/user_projects
-- теперь живут в отдельной control-БД, общей для всех проектов, а не
-- внутри БД конкретного проекта. См. schema_control.sql.
--
-- Историческая ALTER-миграция platform/first_name/last_name (2026-09-05
-- и ранее) уже применена на проде и учтена в текущей структуре
-- schema_projects.sql/schema_control.sql — здесь оставлена не нужна.
